spring:
    cloud:
      gateway:
        globalcors:
          add-to-simple-url-handler-mapping: true
          corsConfigurations:
            '[/**]':
              allowedOrigins: "http://127.0.0.1:5500"
              allowedHeaders:
                - "Origin"
                - "Content-Type"
                - "Accept"
                - "Authorization"
                - "Referer"
              allowedMethods:
                - POST
                - GET
                - OPTIONS
      routes:
      - id: serv-vuelos
          #lb:// cuando se va a acceder a través de Eureka
        uri: lb://servicio-vuelos #http://localhost:8080
        predicates:
          - Path=/svuelos/**


      - id: serv-hoteles
          #lb:// cuando se va a acceder a través de Eureka
        uri: lb://servicio-hoteles #http://localhost:8080
        predicates:
          - Path=/shoteles/**


      - id: serv-reservas
          #lb:// cuando se va a acceder a través de Eureka
        uri: lb://servicio-reservas #http://localhost:8080
        predicates:
          - Path=/sreservas/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_FIRST
          
server:
  port: 7000
eureka:                  
 client:
  serviceUrl:
   defaultZone: http://localhost:8761/eureka 
